create table if not exists public.client_requests (
  id bigint generated by default as identity primary key,
  message text not null,
  attachments jsonb not null default '[]'::jsonb,
  email_id text,
  created_at timestamptz not null default now()
);

alter table public.client_requests enable row level security;

revoke all on public.client_requests from anon, authenticated;
